# Generated by Django 4.2.2 on 2024-12-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_email", "0002_customers_owner_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_cancel_mailing", "Can cancel mailing"),
                    ("can_blok_user", "Can blok user"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
